# -*- coding: utf-8 -*-
"""Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oyj7a7SoLl3Y_bXjt8HzTPBIm3xOE7FJ
"""

#part 1

1. x=2.5 (b.float)
2. b.**
3. b.tuple
4. c.set
5. c.person['age']

#part 2

a=17
b=5
print(a//b) #floor division
print(a%b)  # modulus

numbers=[10,20,30,40,50,60]
print(numbers[1:4])

set_a = {1, 2, 3, 4}
set_b = {3, 4, 5, 6}
print(set_a & set_b)

student = {"name": "John", "score": 85}
student["score"] = 92
student["passed"] = True
print(len(student))

#part 3

#problem 1
c = float(input("Enter a temperature in Celsius: "))
f= (c * 9/5) + 32
print(f"Temperature in Fahrenheit: {f:.2f} F")

#problem 2
import builtins
grades = [78, 85, 62, 90, 85, 95, 78]
unique_grades = list(set(grades))
unique_grades.sort(reverse=True)
max_grade = max(unique_grades)
min_grade = min(unique_grades)
avg_grade = sum(unique_grades) / len(unique_grades)
print("Unique grades (descending):", unique_grades)
print("Maximum grade:", max_grade)
print("Minimum grade:", min_grade)
print(f"Average grade: {avg_grade:.2f}")

#problem 3
frontend_skills = {"HTML", "CSS", "JavaScript", "React"}
backend_skills = {"Python", "SQL", "JavaScript", "Node"}
all_skills = frontend_skills.union(backend_skills)
shared_skills = frontend_skills.intersection(backend_skills)
backend_only = backend_skills.difference(frontend_skills)
print("All skills across both domains:", all_skills)
print("Shared skills:", shared_skills)
print("Backend-only skills:", backend_only)

#problem 4
classroom = {
    "S101": {"name": "Alice", "subjects": {"Math": 88, "Science": 92}},
    "S102": {"name": "Bob", "subjects": {"Math": 75, "Science": 80}}
}
classroom["S103"] = {"name": "Charlie", "subjects": {"Math": 95, "Science": 89}}
alice_scores = classroom["S101"]["subjects"].values()
alice_avg = sum(alice_scores) / len(alice_scores)
print(f"Alice's Average Score: {alice_avg:.2f}")
classroom["S102"]["subjects"]["Math"] = 82
print("Updated Classroom Dictionary:")
print(classroom)

#part 3

#problem 1
bill_amount = 125.50
tax_percentage = 8.0
tip_percentage = 15.0
tax_amount = bill_amount * (tax_percentage / 100)
tip_amount = bill_amount * (tip_percentage / 100)
grand_total = bill_amount + tax_amount + tip_amount
print(f"Original Bill : {bill_amount:.2f}")
print(f"Tax(8%): {tax_amount:.2f}")
print(f"Tip(15%): {tip_amount:.2f}")
print(f"Grand Total: {grand_total:.2f}")

#problem 2
numbers = [12, 45, 2, 91, 33, 24, 88, 50, 19, 73]
middle=numbers[3:7]
print("middle 4 numbers",middle)
numbers.append(100)
print(numbers)
numbers.insert(0,5)
print(numbers)
numbers.sort()
print("Updated list",numbers)
print("length",len(numbers))

#problem 3
inventory = {"laptop": 12,"mouse": 50,"keyboard": 25,"monitor": 8}
inventory["headphones"] = 30
inventory["mouse"] = 45
del inventory["monitor"]
in_stock_items = set(inventory.keys())
discounted_items = {"mouse", "keyboard", "webcam"}
in_stock_and_discounted = in_stock_items & discounted_items
out_of_stock_discounted = discounted_items - in_stock_items
print("In-stock and discounted items:", in_stock_and_discounted)
print("Discounted items out of stock:", out_of_stock_discounted)

#problem 4
employee = ("E402", "Sarah Connor", "Engineering", 75000)
emp_id, emp_name, department, salary = employee
print(f"Employee {emp_name} (ID: {emp_id}) works in {department} with a salary of ${salary}.")
temp_list = list(employee)
temp_list[3] = 82000
employee = tuple(temp_list)
print("Updated Employee Record:", employee)

#problem 5
day_sales = {
    "Monday": {"apples": 10, "bananas": 15, "oranges": 8},
    "Tuesday": {"apples": 12, "bananas": 20, "oranges": 5},
    "Wednesday": {"apples": 8, "bananas": 18, "oranges": 12}
}
total_apples = sum(day_sales["apples"] for day_sales in sales.values())
total_bananas = sum(day_sales["bananas"] for day_sales in sales.values())
print("Total apples sold:", total_apples)
print("Total bananas sold:", total_bananas)
if total_apples > total_bananas:
    print("Apples sold more than bananas.")
elif total_bananas > total_apples:
    print("Bananas sold more than apples.")
else:
    print("Both apples and bananas had identical sales.")

#task 1 (corrected code)
age = int(input("Enter your age: "))
years_to_100 = 100 - age
print(f"You will turn 100 in {years_to_100} years!")

#task 2 (corrected code)
math = 60
science = 40
english = 80
average = (math + science + english) / 3
is_passed = (average >= 50) and (math > 50 or science > 50 or english > 50)
print("Average:", average)
print("Passed:", is_passed)

#task 3(corrected code)
tags = {"python", "coding", "developer"}
user_profile = {
    "username": "coder123",
    "skills": tags,
    "location": ["New York"]
}
first_skill = list(tags)[0]
tags.add("backend")
user_profile["location"].append("USA")
print("First skill:", first_skill)
print("Updated profile:", user_profile)

#task 4(corrected code)
coordinates = (10.5, 20.3, 30.1)
coords_list = list(coordinates)
coords_list[0] = 12.0
coordinates = tuple(coords_list)
numbers = [1, 2, 3, 4, 5]
if 10 in numbers:
    numbers.remove(10)
numbers.sort()
numbers.append(6)
sorted_numbers = numbers
print("Coordinates:", coordinates)
print("Numbers:", sorted_numbers)

#task 5 (corrected code)
inventory = {"apple": 50,"banana": 30,"orange": 20}
grape_qty = inventory.get("grape", 0)
inventory["banana"] += 10
keys_tuple = tuple(inventory.keys())
print("Grape quantity:", grape_qty)
print("Updated inventory:", inventory)
print("Keys tuple:", keys_tuple)